### ISSUE TITLE
fterm workdir

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1030]
fterm mounts into docker only subtree containing fterm itself
It should also mount the subtree containing PWD to allow usage from different directories.

**Comment by janhybs** [comment]
- under windows, entire disk in which current directory resides is mounted.
 - under Linux, [the first child directory in `$HOME` which leads to the flow123d repo directory](https://github.com/flow123d/flow123d/blob/master/bin/fterm#L183-L204) is mounted (if  `$FLOW123D_WORK` is not set), otherwise former is mounted as we agreed upon. This dir is what we call as `<work>`.

Files not under `$HOME/<work>/` are not accessible right now. Do you want to add a permanent mount for the `pwd` as well?

**Comment by jbrezmorf** [comment]
The reason to mount a subtree containing flow123d is probably the development. If we can mount this subtree and pwd as well that will provide desired better consistency between windows and linux installations.
