### ISSUE TITLE
Is the Flow123d can be used to simulate the water pumping process? 

### ISSUE THREAD

**Issue by xuhenry** [flow123d/flow123d#1131]
Dear all,
      I want to simulate the water pumping process with a series of wells? Does the Flow123d can be used in this simulation? 
      Thanks a lot!
Best regards,
Henry

**Comment by jbrezmorf** [comment]
What is the scale of the domain and how many wells? We have used Flow123d
to such tasks, the problem is with proper approximation of the wells.

Flow123d is specialized in models containing both continuum and discrete
fractures. If you need not use this feature
there are commercial tools with a graphical interface, where you can
possibly set up your model more quickly.

**Comment by xuhenry** [comment]
There are about 20 wells in 5km2.  Yes, I know there are some commercial tools that can do this. But if Flow123d can simulate this process, it will be good. Because we can coupling it with the numerical simulation of solid mechanics.
Thanks  a lot!

**Comment by jbrezmorf** [comment]
1. Hydro-mechanical coupling in terms of Biot model is a very new feature, not yet in any released version.
However we would appreciate testing on a real world problem and can provide some support in that case.

2. Such number of wells is treatable. Are you able to prepare the mesh using GMSH tool? You should make wells larger to get reasonable element sizeof the refined elements around wells. We have used  sort of approximation to prescribe physically correct BC on the well walls. 
Do you need also model for the flow in the wells?
