### ISSUE TITLE
systematická chyba v manuálech pro flow123d

### ISSUE THREAD

**Issue by corund7266** [flow123d/flow123d#1190]
v některých případech nelze nalézt výrazy s podrtžítkem, např. "cross_section" není nalezeno na str. 123 v manuálu pro verzi 2.2.1 a stejně tak na straně 128 pro verzi 3.0.3. Nelze nalézt též výraz "max_dt" v obou verzích manuálu. evidentně se jedná o systematickou chybu, která je pravděpodobně i v jiných výrazech obsahujících podtržítko.

**Comment by Paulie14** [comment]
This is caused due to different types of underscores in the doc:
Using LaTeX verbatim `verb'a_b'`, it will print the underscore as expected and can be found by `CTRL+F` in pdf search.

However using `\tt a\_b`, it will not produce the correct underscore. 
This is used heavily both in the written doc and the generated input file reference.

Solution:
We can try using `\symbol{'137}` instead of escaping `\_`
see discussion here for details on different underscores: https://tug.org/pipermail/texhax/2015-February/021542.html

**Comment by jbrezmorf** [comment]
Potvrzeno. `cross_section` se najde pouze v tutoriálech, nikoliv pro klíč `cross_section` v generované dokumentaci. Asi je problém, že tam Latex vloží nějaký jiný znak než klasické podtržítko, možná tím, že to není verbatim. V textu jsou pak názvy proměnných bez podtržítek což je myslím v pořádku pokud bude dohledatelný ten klíč.

**Comment by Paulie14** [comment]
to JL: klíče s podtržítky lze nyní dohledat vynecháním podtržítek, tedy hledej `crosssection` místo `cross_section`

**Comment by corund7266** [comment]
Ano, jde hledat "cross section" s mezerou, v adobe se najde všechno, ikdyž je tam třeba mínus. Jenže teď to vím. Před tím jsem to něvěděl. Jen ještě připomínám, že to platí i např. pro "max_dt".

**Comment by jbrezmorf** [comment]
- [ ] Try to use the special symbol in order to allow the search for `cross_section` etc.
- [ ] Try if we can also find `cross section` with the space.

**Comment by Paulie14** [comment]
Fixed by 7ccd03b512387fc0f86b13daadf1db575c74300c.
