### ISSUE TITLE
Do výstupního MSH se ukládají chybné hodnoty

### ISSUE THREAD

**Issue by milanhokr** [flow123d/flow123d#1199]
Chování F123 je nelogicky odlišné v závislosti na vybraných polích pro výstup, přičemž dochází z části k výstupu špatných hodnot.

Vypočtené pole tlaku ukládané do MSH se chová následovně:
- pokud je output field jen "- pressure_p1", tak ukládané tlaky jsou cca o 100 menší, což nejspíš je hodnota piezo_head zadaná jako počáteční a okrajová podmínka 
- pokud je v output field k tomu navíc "- piezo_head_p0" (tj. dvě pole), tak výsledné hodnoty jsou "správné" (odpovídající okrajovým podmínkám)
Dle BC je head=110 nebo pressure=110-z, rozsah z je -350 až -250, takže tlak by měl být 360 až 470 ale v prvním případě je v rozsahu cca 250 až 350, kromě nultého kroku který není načten z počáteční podmínky (v prvním případě nula, v druhém 90-115 s nějakou perturbací uvnitř - to že ten nultý je vždy divný už jsem si zvykl a není předmětem tohoto komentáře, ale k řešení asi taky je?) 

Zápis do observe_fields je ovšem stejný (tj zřejmě jsou spočtena správná data, ale jen výstup fields je chybný).

Vedle toho se ty dvě zadání liší ve výstupu do water_balance: u jednoho pole nejsou řádky ALL, u dvou polí jsou řádky ALL (nemyslím si, že by spolu mělo souviset).

Chyba se projevuje na Charonu ve v. 3.0.3_dev (odkazy níže), ale také v PC verzi 2.2.1, tj. zřejmě se skrývá už velmi dlouho.

jedno output pole
home\milanhokr\greet2\testOUTtlak\GR-drain_stor.yaml
home\milanhokr\greet2\testOUTtlak\output\
dvě output pole
home\milanhokr\greet2\testOUTtlak\GR-drain_stor2.yaml
home\milanhokr\greet2\testOUTtlak\output2\

**Comment by milanhokr** [comment]
Doplňuju ještě jeden výpočet - ustálený stav, kde je lépe vidět celý gradient mezi nulovým tlakem v tunelu a předepsanou vnější okrajovou podmínkou. Spočítané toje na PC 221 a jen nakopírované na charon:
home\milanhokr\greet2\testOUTtlak\ustalena_v221\
Na obrázcích je vidět, že pole je kvalitativně takřka stejné, jen ten rozsah jiný (tj. není rozdíl jen v odečtení "konstanty" ani přímo piezo_head (to má rozsah -300 tunel a +110 vnějšek) - "spravny"=výstup tlak+piezo, "chybny"=výstup jen tlak.
![Spravny](https://user-images.githubusercontent.com/56994529/78109590-c5c08180-73f9-11ea-89ff-5e447aa607b1.png)
![Chybny](https://user-images.githubusercontent.com/56994529/78109608-cfe28000-73f9-11ea-9a02-e69c67bc9962.png)

**Comment by jbrezmorf** [comment]
Když to shrnu, tak problem je, ze:

`- pressure_p1` dává špatné výsledky, pokud se zároveň nevyztupuje 
`- piezo_head_p0`. Přičemž výstup v observe i bilancích je v obou případech dobře.

Rozumím správně?

**Comment by milanhokr** [comment]
Ano.
Plus ta drobnost s chybějícím řádkem ALL v bilanci.

**Comment by Paulie14** [comment]
I confirm the problem with `pressure_p1`. It used element pressure values and if these were not computed before, it gave wrong results.
Fixed by 308ae1ab223834649209feb8026d6018e5dd35ee in 3.0.3 branch.
If necessary, we can create 3.0.4 version with this fix.
This bug is not in new dev branches since there we use the general interpolation scheme. (and I also checked the results..)

Next, I will check the balance thing..

**Comment by Paulie14** [comment]
The `ALL` region is evaluated only if the `cumulative` Balance is true, since it includes the cumulative values of the quantities.

The problem is however somehow hidden in the yaml input file.
In both input files there are two balance records, which should definitely be avoided! 
```
balance: {}
balance:
  cumulative: true
```

The first record means to create Balance object without the cumulative data, the second otherwise.
If I used only one the records, it worked correctly as expected.

However I was not able to explain, when it has both records at the same time, why one of the file computed the cumulative values and the other did not.

For devs
balance.cc:147 ```cumulative_ = in_rec.val<bool>("cumulative");```
gives true in one case and false in the other. I do not know why since the difference between the input files is only due to output of `piezo_head_p0`.

**Comment by Paulie14** [comment]
Will continue in #1219.
