### ISSUE TITLE
self-conteined package with shared libraries

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#183]
Make a self-contined package for Linux is problematic. We can not simply make everything static 
1) some libraries (python) are only shared in standard distributions
2) system (gcc) libraries are shared

Current state:
We detect shared libraries of the linked binary using 'ldd' command. "system libraries" determined by experimenting are put to lib/system, while other libraries are put into lib directory of the package. Moreover, we add "$ORIGIN/../lib" into RPATH of the flow123d binary, so the loader can find non-system libraries placed relative to the binary. If the target system has libgfortran everything seems to run smoothly as system libraries from target system are used. If libgfortran is not available we must switch to libraries placed into lib/system including loader "ld-linux-*.so". Then we can run binary as follows:

```LD_LIBRARY_PATH=`pwd`/lib/system lib/system/ld-linux-x86-64.so bin/flow123d ```

 TODO:
1) reconsider static linking, it could be possible with our own python build and
without gfortran (NO OPTION)
2) in order to robustly support dynamic linking we should have wrapper script of binary to run provided loader as mentioned above
3) make our own build of python as a constant and controled package containing what we may need e.g. NumPy etc. (NO OPTION)

**Comment by jbrezmorf** [comment]
Ask a unix specialist about best practice.

**Comment by x3mSpeedy** [comment]
## Research related to this problem
### Testing package downloaded from flow.nti.tul.cz
Downloaded [this](http://flow.nti.tul.cz/packages/0.0.master/flow123d_0.0.master_linux_x86_64.tar.gz) package
<hr />

1. Standard execution: ```bin/flow123d ```

  According to [this discussion](http://stackoverflow.com/questions/7251573/gcc-relocation-error-at-runtime) and [this page](https://docs.oracle.com/cd/E19120-01/open.solaris/819-0690/chapter3-5/index.html) problem lies with linker **```ld-linux-x86-64.so```**. Error is complaining on shared library **libc.so.6**
  ```
  bin/flow123d: relocation error: /home/jan-hybs/flow/bin/../lib/libpthread.so.0: symbol __getrlimit, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
  ```
  <hr />
2. Wrapper execution: ```./wrapper.sh```

  content of ```wrapper.sh```:
  ```bash
  #!/bin/bash
  export LD_LIBRARY_PATH=`pwd`/lib/system
  lib/system/ld-linux-x86-64.so.2 bin/flow123d
  ```
  Result is surprisingly some **python** error which would indicate that program got over problematic linker part or linker uses some python when linking libs
  ```py
  Traceback (most recent call last):
    File "/usr/lib64/python2.7/site.py", line 563, in <module>
      main()
    File "/usr/lib64/python2.7/site.py", line 545, in main
      known_paths = addusersitepackages(known_paths)
    File "/usr/lib64/python2.7/site.py", line 272, in addusersitepackages
      user_site = getusersitepackages()
    File "/usr/lib64/python2.7/site.py", line 247, in getusersitepackages
      user_base = getuserbase() # this will also set USER_BASE
    File "/usr/lib64/python2.7/site.py", line 237, in getuserbase
      USER_BASE = get_config_var('userbase')
    File "/usr/lib64/python2.7/sysconfig.py", line 578, in get_config_var
      return get_config_vars().get(name)
    File "/usr/lib64/python2.7/sysconfig.py", line 524, in get_config_vars
      _init_posix(_CONFIG_VARS)
    File "/usr/lib64/python2.7/sysconfig.py", line 408, in _init_posix
      from _sysconfigdata import build_time_vars
    File "/usr/lib64/python2.7/_sysconfigdata.py", line 6, in <module>
      from _sysconfigdata_nd import *
  ImportError: No module named _sysconfigdata_nd
  ```
<hr />
3. Copying libs from ```lib/system/``` to ```lib/``` and standard ```bin/flow123d```
  Result reports same kind of error like in **case 1** but is complaining on **different** shared library. Error is complaining on shared library **ld-linux-x86-64.so.2** (linker lib).

  ```
  bin/flow123d: relocation error: /home/jan-hybs/flow/bin/../lib/libc.so.6: symbol _dl_starting_up, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
  ```

### Testing dependencies
When running ldd (listing library dependencies) on flow123d bin from downloaded packgage there are two dependencies which are not in **relative** form. From official documentation about [ld-linux](http://linux.die.net/man/8/ld-linux) we can see that using ```gcc -Wl,-rpath,'$ORIGIN/../lib'``` is working and path is correct but some libs are still using absolute path.

> **$ORIGIN and rpath**
> ld.so understands the string $ORIGIN (or equivalently ${ORIGIN}) in an rpath specification (DT_RPATH or DT_RUNPATH) to mean the directory containing the application executable. Thus, an application located in somedir/app could be compiled with gcc -Wl,-rpath,'$ORIGIN/../lib' so that it finds an associated shared library in somedir/lib no matter where somedir is located in the directory hierarchy. This facilitates the creation of "turn-key" applications that do not need to be installed into special directories, but can instead be unpacked into any directory and still find their own shared libraries.

Shared object ```linux-vdso.so.1``` appears to be injected by kernel [source](http://stackoverflow.com/questions/26266641/why-would-the-same-binary-want-linux-vdso-so-1-on-one-64-bit-rhel-5-4-server-and#answer-26327207).

```bash
$> ldd bin/flow123d
```
<pre>
<b>linux-vdso.so.1      => (0x00007fffec5da000)</b>
libpython2.7.so.1.0  => /home/jan-hybs/flow/bin/../lib/libpython2.7.so.1.0
libbz2.so.1          => /home/jan-hybs/flow/bin/../lib/libbz2.so.1
libz.so.1            => /home/jan-hybs/flow/bin/../lib/libz.so.1
libgfortran.so.3     => /home/jan-hybs/flow/bin/../lib/libgfortran.so.3
libquadmath.so.0     => /home/jan-hybs/flow/bin/../lib/libquadmath.so.0
librt.so.1           => /home/jan-hybs/flow/bin/../lib/librt.so.1
libpthread.so.0      => /home/jan-hybs/flow/bin/../lib/libpthread.so.0
libdl.so.2           => /home/jan-hybs/flow/bin/../lib/libdl.so.2
libX11.so.6          => /home/jan-hybs/flow/bin/../lib/libX11.so.6
libmpichf90.so.10    => /home/jan-hybs/flow/bin/../lib/libmpichf90.so.10
libm.so.6            => /home/jan-hybs/flow/bin/../lib/libm.so.6
libmpichcxx.so.10    => /home/jan-hybs/flow/bin/../lib/libmpichcxx.so.10
libstdc++.so.6       => /home/jan-hybs/flow/bin/../lib/libstdc++.so.6
libmpich.so.10       => /home/jan-hybs/flow/bin/../lib/libmpich.so.10
libopa.so.1          => /home/jan-hybs/flow/bin/../lib/libopa.so.1
libmpl.so.1          => /home/jan-hybs/flow/bin/../lib/libmpl.so.1
libgcc_s.so.1        => /home/jan-hybs/flow/bin/../lib/libgcc_s.so.1
libc.so.6            => /home/jan-hybs/flow/bin/../lib/libc.so.6
<b>/lib64/ld-linux-x86-64.so.2 (0x00007f07e8409000)</b>
libutil.so.1         => /home/jan-hybs/flow/bin/../lib/libutil.so.1
libxcb.so.1          => /home/jan-hybs/flow/bin/../lib/libxcb.so.1
libXau.so.6          => /home/jan-hybs/flow/bin/../lib/libXau.so.6
</pre>

It is necessarily to provide correct linker (ld-linux) since using the one available on platform throws error. Event when forcing packed linker error lies elsewhere.

**Comment by x3mSpeedy** [comment]
After some Googling it was confirmed that when using **wrapper** flow123 **works**, but on ubuntu and ubuntu-like system there is [bug](https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/1115466) which caused error ```ImportError: No module named _sysconfigdata_nd```. After bug fix we finally can see 

```
MPI size: 1
This is Flow123d, version 0.0.master revision: jenkins-Flow123d-linux-release-multijob-384
Branch: master
Build: Nov  7 2015, 03:33:00 flags: -O3 -DNDEBUG -Wall -Wno-unused-local-typedefs -std=c++11
Fetch URL:  https://github.com/flow123d/flow123d.git
```

What strikes me is that flow123d is using **embedded python** yet error occurred when using **system python**. Perhaps we are not truly using embedded python or perhaps there is need for system python in order use embedded one.

It would be handy to have defined specific argument to main program which would return version on python. e.g.:
```bash
bin/flow123d --python-version
```
output would be result from this python expression
```py
import sys
print sys.version
```

output:
```
2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
```
<hr />

Wrapper works but is not stable. Calling flow123d with argument ```--version``` will cause error: 
```
This is Flow123d, version 0.0.master revision: jenkins-Flow123d-linux-release-multijob-384
Branch: master
Build: Nov  7 2015, 03:33:00 flags: -O3 -DNDEBUG -Wall -Wno-unused-local-typedefs -std=c++11
Fetch URL:  https://github.com/flow123d/flow123d.git
bin/flow123d: řádek 19: 25849 Neoprávněný přístup do paměti (SIGSEGV) `pwd`/lib/system/ld-linux-x86-64.so.2 bin/flow123d_ $@
```

But running simple test, e.g.: 
```bash
bin/flow123d -s tests/03_transport_small_12d/flow_implicit.con
```
will compute problem and produce results but still fails when calling python to convert. **This is the same error which happens on *Windows* platform!** so solving this error could possible solve #354 
```
...
End of simulation at time: 1.000000
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<PythonLoader::ExcPythonError>'
  what():  

--------------------------------------------------------
Program Error: Python Error: No module named _struct


** Diagnosting info **
/home/builder/jenkins/F123-linux-release/flow123d/src/system/python_loader.cc(126): Throw in function static void PythonLoader::check_error()
Dynamic exception type: N5boost16exception_detail10clone_implIN12PythonLoader14ExcPythonErrorEEE
[P20EI_PythonMessage_TAG] = No module named _struct

** Stacktrace **
  0  PythonLoader::check_error()
  1  PythonLoader::load_module_by_name(std::string const&)
  2  Profiler::transform_profiler_data(std::string const&, std::string const&)
  3  Application::~Application()
  4  main

--------------------------------------------------------

bin/flow123d: řádek 19: 26091 Neúspěšně ukončen (SIGABRT)        `pwd`/lib/system/ld-linux-x86-64.so.2 bin/flow123d_ $@
```

note wrapper now must alter PYTHONPATH variable containing path to our custom modules. wrapper now looks like this:

```bash
#!/bin/bash
export LD_LIBRARY_PATH=`pwd`/lib/system
PP=${PYTHONPATH}
PP=${PP}:`pwd`/lib/python2.7/site-packages
PP=${PP}:`pwd`/lib/python2.7
PP=${PP}:`pwd`/lib/flow123dc
PP=${PP}:`pwd`/include/python2.7
PP=${PP}:`pwd`/include/ 
export PYTHONPATH=${PP}
lib/system/ld-linux-x86-64.so.2 bin/flow123d $@
```

**Comment by x3mSpeedy** [comment]
Issue seems to be that we are copying wrong python location. CMakeLists.txt does copy 

<pre>/usr/<b>lib</b>/python2.7</pre>

but we mainly want to copy
<pre>/usr/<b>lib64</b>/python2.7</pre>

The most correct way to copy **entire** python would be to copy each entry from python path
```py
import sys
print '\n'.join([path for p in sys.path if path])
```
will produce list of all path **required** for python correct behavior. It is also important to keep sys.path since later on we need to supply correct PYTHONPATH in wrapper script.
Result from python call looks like this:

```
/usr/lib64/python27.zip
/usr/lib64/python2.7
/usr/lib64/python2.7/plat-linux2
/usr/lib64/python2.7/lib-tk
/usr/lib64/python2.7/lib-old
/usr/lib64/python2.7/lib-dynload
/usr/lib64/python2.7/site-packages
/usr/lib/python2.7/site-packages
```

I suggest to copy every location from this list to ```lib``` or other folder dedicated to python but keep structure to PYTHONPATH can be set correctly. Structure would look like this:
```
bin
 | -- flow123d (wrapper)
 | -- flow123dbin (binary file)
tests (not changed)
 | -- ...
 | -- ...
include (not changed)
 | -- deal.II
 | -- python2.7
lib
 | -- usr
       | -- lib
       |     | -- python2.7
       |     |       | -- site-packages
       | -- lib64
             | -- python2.7
             |       | -- site-packages
             |       | -- lib-dynload
             |       | -- lib-tk
             |       | -- lib-old
```

In wrapper we would simply prepend each path entry.  What do you think @jbrezmorf ?

**Comment by jbrezmorf** [comment]
Well, having ./lib/usr/lib/python* and ./lib/usr/lib64/python*
is ugly and there is a pitfall that windows packaging tool NSIS have
quite limited maximal path length, which was probably reason why I
rather remove the prefix. However it seems  simple to remove /usr/lib*
from every path in PYTHON_PATH, isn't it? Moreover we can not leave
PYTHON_PATH as it is anyway, since it contains absolute paths like
/usr/lib64/, but we need paths relative to $FLOWDIR/lib.

H.

On 01/07/2016 04:03 PM, Jan Hybš wrote:
> Issue seems to be that we are copying wrong python location.
> CMakeLists.txt does copy
> 
> /usr/*lib*/python2.7
> 
> but we mainly want to copy
> 
> /usr/*lib64*/python2.7
> 
> The most correct way to copy *entire* python would be to copy each entry
> from python path
> 
> import sys
> print '\n'.join([path for p in sys.path if path])
> 
> will produce list of all path *required* for python correct behavior. It
> is also important to keep sys.path since later on we need to supply
> correct PYTHONPATH in wrapper script.
> Result from python call looks like this:
> 
> |/usr/lib64/python27.zip /usr/lib64/python2.7
> /usr/lib64/python2.7/plat-linux2 /usr/lib64/python2.7/lib-tk
> /usr/lib64/python2.7/lib-old /usr/lib64/python2.7/lib-dynload
> /usr/lib64/python2.7/site-packages /usr/lib/python2.7/site-packages |
> 
> I suggest to copy every location from this list to |lib| or other folder
> dedicated to python but keep structure to PYTHONPATH can be set
> correctly. Structure would look like this:
> 
> |bin | -- flow123d (wrapper) | -- flow123dbin (binary file) tests (not
> changed) | -- ... | -- ... include (not changed) | -- deal.II | --
> python2.7 lib | -- usr | -- lib | | -- python2.7 | | | -- site-packages
> | -- lib64 | -- python2.7 | | -- site-packages | | -- lib-dynload | | --
> lib-tk | | -- lib-old |
> 
> In wrapper we would simply prepend each path entry. What do you think
> @jbrezmorf <https://github.com/jbrezmorf> ?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flow123d/flow123d/issues/183#issuecomment-169687643>.
> 

-- 
------------------------
Mgr. Jan Brezina, Ph. D.
Technical University in Liberec, New technologies institute
http://www.nti.tul.cz/cz/WikiUser:Jan.Brezina

**Comment by x3mSpeedy** [comment]
In current state it is possible to remove some prefix string. We can have problem in future if we are to use other python modules which are not is ```usr/lib*```. Hopefully removing prefix will not change python behavior (some module uses path knowledge to work with other modules).
@jbrezmorf would **this** be acceptable for now?

<pre>
bin
 | -- flow123d (wrapper)
 | -- flow123dbin (binary file)
tests (not changed)
 | -- ...
 | -- ...
include (not changed)
 | -- deal.II
 | -- python2.7
<b>lib
 | -- python2.7
 |       | -- site-packages
lib64
 | -- python2.7
 |       | -- site-packages
 |       | -- lib-dynload
 |       | -- lib-tk
 |       | -- lib-old
</b>
</pre>

**Comment by jbrezmorf** [comment]
This scheme is perfect.


On 01/08/2016 11:12 AM, Jan Hybš wrote:
> In current state it is possible to remove some prefix string. We can
> have problem in future if we are to use other python modules which are
> not is |usr/lib*|. Hopefully removing prefix will not change python
> behavior (some module uses path knowledge to work with other modules).
> @jbrezmorf <https://github.com/jbrezmorf> would *this* be acceptable for
> now?
> 
> bin
>  | -- flow123d (wrapper)
>  | -- flow123dbin (binary file)
> tests (not changed)
>  | -- ...
>  | -- ...
> include (not changed)
>  | -- deal.II
>  | -- python2.7
> *lib | -- python2.7 | | -- site-packages lib64 | -- python2.7 | | --
> site-packages | | -- lib-dynload | | -- lib-tk | | -- lib-old *
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flow123d/flow123d/issues/183#issuecomment-169953723>.
> 

-- 
------------------------
Mgr. Jan Brezina, Ph. D.
Technical University in Liberec, New technologies institute
http://www.nti.tul.cz/cz/WikiUser:Jan.Brezina

**Comment by x3mSpeedy** [comment]
Current status is:
* Libs are now not separated, (```lib/system/``` and ```lib/```).
* Python libs are in ```lib/``` and ```lib64/``` folders. Copying the python files is done using **```rsync```** since structure must be preserved and ```cp``` command [does not create folder](http://stackoverflow.com/questions/947954/how-to-have-the-cp-command-create-any-necessary-folders-for-copying-a-file-to-a) and we dont know structure beforehand. ```rsync``` is therefore used with trick to preserve only part of path (we do not want to create ```usr/```)
* In CMakeListsthere is now variable ```FLOW_WRAPPER``` which is content of wrapper file, which will be later on packed in tar.gz. CMakeLists will create only **part of** wrapper file wince we do not know loader ld-linux lib location so in ```copy_shared_libs.sh``` we detect loader in complete wrapper file. In CMakeLists there is INSTALL which will copy wrapper to ```bin/``` folder. I tested archive and it is now **working** when using wrapper.

**Without wrapper**
```bash
$ ./bin/flow123d
./bin/flow123d: relocation error: /home/jan-hybs/Dokumenty/flow-embedded/Flow123d-1.8.JHy_embedded_python-Linux/bin/../lib/libc.so.6: symbol _dl_starting_up, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```
**With wrapper**
```bash
$ ./bin/flow123d_wrapper.sh
MPI size: 1
This is Flow123d, version 1.8.JHy_embedded_python revision: release_1.8.2-937-gd1ad6c6
Branch: JHy_embedded_python
Build: Jan 13 2016, 11:00:07 flags: -O3 -DNDEBUG -Wall -Wno-unused-local-typedefs -std=c++11
Fetch URL:  https://github.com/flow123d/flow123d.git
Usage error: The main input file has to be specified through -s parameter.
```
**Generated wrapper contains following**
```bash
#!/bin/bash
PYTHONPATH=${PYTHONPATH}:./lib64/python27.zip
PYTHONPATH=${PYTHONPATH}:./lib64/python2.7
PYTHONPATH=${PYTHONPATH}:./lib64/python2.7/plat-linux2
PYTHONPATH=${PYTHONPATH}:./lib64/python2.7/lib-tk
PYTHONPATH=${PYTHONPATH}:./lib64/python2.7/lib-old
PYTHONPATH=${PYTHONPATH}:./lib64/python2.7/lib-dynload
PYTHONPATH=${PYTHONPATH}:./lib64/python2.7/site-packages
PYTHONPATH=${PYTHONPATH}:./lib/python2.7/site-packages
PYTHONPATH=${PYTHONPATH}:./lib/flow123d
export PYTHONPATH=${PYTHONPATH}
export LD_LIBRARY_PATH=./lib
lib/ld-linux-x86-64.so.2 bin/flow123d linux
```


What remains is:
- [ ] to rename flow123d bin file to something else and rename wrapper to ```flow123d``` so user do not notice change. I tried to generate different bin name from the start but there were still some errors so I suggest to do this step during INSTALL phase
- [ ] to create windows wrapper to inject python path only (or somehow embed python path knowledge into binary)

**Comment by jbrezmorf** [comment]
Few notes:
- using rsync is problematic since it creates another unnecessary dependence. The problem can be resolved by simple python script or possibly using some CMake functionality. We can discuss this in particular pull request.
- Better solution then FLOW_WRAPPER variable is a file template, see e.g. template CMake/rev_num_h_template and its usage in CMake/Modules/Flow123d_git_rev_num vie. the configure_file command.
- I'm supicious if the proposed wrapper works also when calling the wrapper from any directory since paths are relative.
- rename of flow123d must be done during install by CPack
- Possibly we may avoid a wrapper setting Windows register in proper way. According to 
[ Windows doc](https://msdn.microsoft.com/en-us/library/windows/desktop ee872121%28v=vs.85%29.aspx) one can set PATH variable specific to particular application.
I think that Python search PATH for its files so it may be the way. But since it requires yet lot of testing a usage of a BAT wrapper may be preferred  currently.

**Comment by x3mSpeedy** [comment]
Ad relative calling. I already changed that in 944544bc2ddac44c4e53c9dd4766142f5bafb56c:
```bash
#!/bin/bash
DIR="$(dirname $(dirname $0))"
PYTHONPATH=${PYTHONPATH}:${DIR}/lib64/python27.zip
PYTHONPATH=${PYTHONPATH}:${DIR}/lib64/python2.7
PYTHONPATH=${PYTHONPATH}:${DIR}/lib64/python2.7/plat-linux2
PYTHONPATH=${PYTHONPATH}:${DIR}/lib64/python2.7/lib-tk
PYTHONPATH=${PYTHONPATH}:${DIR}/lib64/python2.7/lib-old
PYTHONPATH=${PYTHONPATH}:${DIR}/lib64/python2.7/lib-dynload
PYTHONPATH=${PYTHONPATH}:${DIR}/lib64/python2.7/site-packages
PYTHONPATH=${PYTHONPATH}:${DIR}/lib/python2.7/site-packages
PYTHONPATH=${PYTHONPATH}:${DIR}/lib/flow123d
export PYTHONPATH=${PYTHONPATH}
export LD_LIBRARY_PATH=${DIR}/lib
${DIR}lib/ld-linux-x86-64.so.2 bin/flow123d $@
```
Ad template wrapper generation:
Problem is, that pythonpath length can vary but I would also use some kind of template.

**Comment by jbrezmorf** [comment]
- flow123d may be renamed by CPack option EXPORT. suggested name: flow123d.bin
- wrapper should be made as part of copy_shared_libs-sh since only in this script we know the name of the loader
- use cmake -E copy_directories to copy PYTHON libraries if COPY_PYTHON is set.
