### ISSUE TITLE
Remove MHDofHandler

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#232]
Dependes on #358 

Seems that MHDofhandler does contain only data about discontinuous velocity and could be replaced by FeValues and/or FieldNumerical.
The aim is to pass only Fields between equations.

**Comment by Paulie14** [comment]
1) Create FieldFE in DarcyFlow for velocity.
Method in DarcyFlowMH for creation of DofHandler of velocity. (Hack for renumbering sides from DG)

2) Pass FieldFE to transport classes and use it instead of MHDofHandler.
3) Use FEValues in DarcyFlow assembly.

**Comment by Paulie14** [comment]
encountered problems:
1) how should I replace mhdofhandler->time_changed(), when the FieldFE is passed to transport instead?

2) I want to add velocity FieldFE into EqData to pass to transport as other fields (e.g. cross section).
the problem is that FieldFE and FieldAlgorithmBase is not derived from FieldCommon, so I cannot add it to field set:

    error: no matching function for call to ‘DarcyFlowMH::EqData::add_field(FieldFE<3, FieldValue_<3,1, double> >*, std::string, const char [18])’
     ADD_FIELD(velocity, "Darcian velocity.");
     no known conversion for argument 1 from ‘FieldFE<3, FieldValue_<3, 1, double> >*’ to ‘FieldCommon*’

therefore I cannot pass to transport data... How can this be done?

**Comment by Paulie14** [comment]
encountered problem n.2 solved.

new question: Why there is not implemented zero_time_step method in DarcyFlow (although it is called)? 
I want to pass a petsc serial velocity vector to FieldFE but I need to write it in all classes - steady and unsteady, because it is needed in output_data() which is called (I think inconsistently) in unsteady classes in constructor - not in zero_time_step...
I think that all the computing stuff - like creating linsys, setting initial condition, should be done in zero_time_step..

**Comment by Paulie14** [comment]
problem n.1 also solved

encountered bigger problems:
- parallel velocity (or pressure) vector cannot be used until we have parallel mesh
- computing flux/velocity by FieldFE is expensive at the moment, as we do not support any getters for dofs. Computing values of FE RT0 in field makes explicit transport matrix assembly 5x slower!

found bugs in fields:
- multifield set_time_results_ unset in set_time (solved)
- circular buffer history - comparing only pointers in history, not actual history points - we need to be able to put the same field with different times in history for velocity (solved)

**Comment by jbrezmorf** [comment]
Summary of blockers for this issue
- [ ] Need faster interface to evaluate values of FieldFE (using points on reference element) 
- [ ] design and implement parallel mesh and dofhandlers (with necessary ghost elements), in particular we need velocities on local domains of transport
  Do we really need velocities on ghost elements?
- [ ] Fix bugs in fields, near to be done.
