### ISSUE TITLE
Interupted calcualtion

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#333]
Output fields in a form that allows restarted calculation (caused by fault or by wrong setting of end_time).
Currently this could be possible with output into GMSH and some CON tweeking.
- test if it is possible with current functionality
- describe it in doc

**Comment by Paulie14** [comment]
Curretly (without multifields), we are unable to set initial condition for more than one substance by FieldElementwise.
We would like to do something like this:
```
 init_conc = [
             { 
              TYPE="FieldElementwise",
              gmsh_file = "./test_a/transport.msh",
              field_name = "age"
            },
            { 
              TYPE="FieldElementwise",
              gmsh_file = "./test_a/transport.msh",
              field_name = "U235"
            }
]
```
This problem is also connected with the gmsh file structure: 
Now, we can read from input or send to output each substance in separate section.
Second option is to be able to work with substances organized in columns. (We can probably read this
structure but we cannot create it in output.)

We should think more about restarting the computation, trying to avoid creating a new input file by changing all fields to elementwise type...

**Comment by jbrezmorf** [comment]
Depends on implementation and usage of multifields #225

**Comment by jbrezmorf** [comment]
Definitive solution is to provide output of internal solution FieldFE into our own format and 
provide FieldFE input capability.

**Comment by jbrezmorf** [comment]
duplicate of #680
