### ISSUE TITLE
Transport CFL condition for sourcs

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#338]
- Implement combined Neuman and Newton BC in ConvectiveTransport, see #367
- Constrain time step in convective transport by CFL condition for sources.
- Do we need some form of CFL condition in reactions and/or dual porosity?
- Add descriptions to timestep constrains and report description of active constrains in the log.
- Document all possible CFL conditions that influence the timestep.

**Comment by Paulie14** [comment]
Notes:
Divide CFL computation in explicit transport from assembly.
Then suggest passing CFL condition among equations.

**Comment by Paulie14** [comment]
prerequisite: 
implement source term in the form "s(cs - c[t])" not with difference"s(cs-c[t-1])" 
This way it contributes into diagonal of the trasnport matrix (saved in separate vector)
this is done by commit ffedcd03f3563bd2df298a3eab6c85d865b5b790

**Comment by Paulie14** [comment]
How to compute CFL condition?
condition is in the form timestep < 1 / (matrix_part + source_part),
where matrix_part is due to flow and is assembled in matrix assembly,
on the other hand source_part is assembled separately with source term assembly (because matrix assembly is independent of substances data)

To compute the condition correctly, I would need to save matrix_part in all elements in a parallel vector and source_part in another one. Then add the vectors and find its maximum.
Is this the correct way?

**Comment by jbrezmorf** [comment]
Yep. Petsc matrix have function MatGetDiagonal to this end. Soon we should also move to deal.ii linear algebra interface.

**Comment by jbrezmorf** [comment]
Is this completed or something remain to finish?

**Comment by Paulie14** [comment]
- I didn't do anything with BC
- constraint by sources is done
- I didn't do anything about the constraints from reactions yet
- description of constraints are now being discussed in pull request
- I didn't write about CFL in documentation yet

**Comment by jbrezmorf** [comment]
Time step constraint messages implemented in pull: #493
Reactions postponed to issue #552.
Documentation postponed to issue #553
