### ISSUE TITLE
HTML manual

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#343]
- [x] Make HTML formater
- [x] publish HTML version of the manual on the web.

**Comment by jbrezmorf** [comment]
Formater done in 76d860fd6a

**Comment by x3mSpeedy** [comment]
When packing (jenkins step ```make doc```) HTML documentation as created, and when publishing documentation is uploaded to flow.nti.tul.cz server.
Example:
http://flow.nti.tul.cz/packages/0.0.JHy_ist_formatter/htmldoc/

I suggest to also add link from ```flow123d.github.io``` to ```flow.nti.tul.cz```

**Comment by jbrezmorf** [comment]
Sure.  Add links to flow123d.github.io to appropriate version. Currently just for master. 
Distinguish  "User manual PDF" and "User manual HTML" in side menu.

**Comment by x3mSpeedy** [comment]
Situation **before** was: shown ```relative-date```, when mouse overed shown ```precise-date```
Situation **now** is: shown ```precise-date (relative-date)```, when mouse overed shown ```relative-date```
![image](https://cloud.githubusercontent.com/assets/894428/9721629/d097db7c-559e-11e5-8083-253dc9326fca.png)

Do you want to remove relative date as well? It's w´quite useful in new build, since you can see right away when was it build.

**Comment by jbrezmorf** [comment]
Just different issue, but great.

**Comment by x3mSpeedy** [comment]
Links were added (only ```master``` branch for now, but there is no html file created since there was bug in python lib). Also I found and [fix](https://github.com/flow123d/flow123d.github.io/commit/85856c542cb6a4557b3970d337daec7ecd4d3035) the bug which was popping up recently.
