### ISSUE TITLE
Change numberings of reference element

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#359]
Depends on #358.
- [x] Try to change numberings of reference element according to the proposal in mesh/ref_element.hh.
- [x] Fix all code that depends on particular numbering, make all depend only on data provided by reference element
- [x] Merge our reference element with that provided by Viktor Fris (see branch VF_fast_23d):
- [x] Check that VF code do not depend on particular numbering as well
- [x] Possibly add new methods into mesh/ref_element.hh

**Comment by Paulie14** [comment]
I want to look at the VF branch so I can take care of this issue. 

I have already tried applying VF ref element into master and it works perfectly (up to raw_output because sides are switched, and old_fbc which needed renumbering arrays edited).

Is there any important difference between branches VF_13d and VF_23d or is it "only" functionality 13d - 23d?

**Comment by jbrezmorf** [comment]
partly resolved in  0b26168

**Comment by jbrezmorf** [comment]
- [  ] Upgrade Armadillo
- [  ] Review barycentric coords, use classical ones since they match numbering of vertices, allowing simple interpolation.
- [ ] provide a conversion to local coords and back (easy in armadillo)
- [ ] simplify code for observe points (clip method) using methods from intersection branch and new Armadillo functions
- [ ] Try to replace interact with an aux class in order to avoid problematic template call :
	`RefElement<>:: template interact<1,2>(i)`  e.g.
	`RefElement<dim>::subelement<sub_dim>(i_sub_el).interact<out_dim>()
	at least give examples in doc.

**Comment by Paulie14** [comment]
Not sure if all is addressed at me..
About barycentric coords: We decided that it is currently better to use VF barycentric coords inside intersection classes and stick to ref element bary coords everywhere else.
There are classes ("output interface") IntersectionLocal and IntersectionPoint, which already converts IntersectionLocalAux ("internal intersection object") and provides local coordinates instead of bary coords.

If you use actual numbers for all the template parameters, you do not have to write "template".
In code templated by dim, you have to.. Actually I did not need to do that, so I did not care....

I also thought about unification for the numbers "n_something" in the similar fashion: RefElement<3>::count<2>

**Comment by jbrezmorf** [comment]
This was just to mention my findings somewhere. The schedule is like:
1. finish release 2.0.0 (some duplicate temporary changes to ref_element)
2. merge PE_intersections into 2.1.0
3. finish ref_element considering notes above

**Comment by Paulie14** [comment]
Note:
We agreed, that the most usual barycentric coordinates are of form [c, x, y, z], with c being the complement coordinate. This needs to be changed in RefElement, where it is [x, y, z, c].

**Comment by Paulie14** [comment]
Note:
We agreed, that the most usual barycentric coordinates are of form [c, x, y, z], with c being the complement coordinate. This needs to be changed in RefElement, where it is [x, y, z, c].
