### ISSUE TITLE
possible problem in profiler formater

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#404]
in test 20 we observed an error:
Error when executing Python: 'NoneType' object is not iterable

1) The error message is not satisfactory. The code in sys_profiler, should use PythonLoader::check_error to check error and report it with backtrace.
     Moreover, it should be reported as a warning if it doesn't result in crash.
2) Should investigate source of the actual error. However we can not reproduce it.

**Comment by x3mSpeedy** [comment]
Sadly I also cannot reproduce this error.
In ```sys_profiler.cc``` I try to use fasede class ```PythonLoader``` as much as possible since it contains test for python error, but in some cases (e.g. calling method) I have to rely on raw Python C API.

I added ```PythonLoader::check_error()``` in 5eb8403ffa177e54508d964c47dff4f8d30bb74d to last place which wasn't tested for error but I'm afraid the result would have been the same if error occured and test was there.

Python reporting ``` 'NoneType' object is not iterable``` is standard Python built in error and its message I cannot change. In output there should have been more info to it (traceback where error occurred, but I cannot find appropriate build). But error indicates that some for loop couldnot be done since given object was None. Only thing I can think of is loading **broken** or **empty** json file and try to transform it.

I added (in 3ab55d8e1e3fd08d00a952d94951fcefdece2d4d) logging support in profiler formatter so hopefully in case some error occurs, we will know more.

**Comment by jbrezmorf** [comment]
There was no backtrace in the build output. I guess that some Python code was called, throwing that exception which were possibly detected in Flow123d, however the error message was reported without backtrace, or backtrace could not be retrieved. 
We should discuss possible improvements in catching and reporting errors from Python code.
I leave this open until release of 2.0.0 and close it if it does not reappear.

**Comment by jbrezmorf** [comment]
Backtrace added in the branch JB_profiling_frames. 1cb4ec3
Similar error resolved.
