### ISSUE TITLE
Test distribution under Docker

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#582]
Docker may offer:
- ultimate resolution of portability issues
- simplify usage of libraries (no need of CMake install rules) 
- may allow also solution for GeoMop

In order to adopt Docker we need to test:

1) Rychlost Dockeru pod Windows orientačně vs. běh pod Cygwin
2) Porovnat běh flow123d na benchmarkových úlohách, pro:
- Windows pod Cygwin
- Windows pod Dockerem
- Linux nativně
- Linux pod Dockerem (podle dostupných zdrojů o cca 5% pomalejší než nativně pod Linuxem)

Předpoklad je, že verzi instalovanou přes Docker budou lidi používat na menších problémech, takže zpomalení pod 50% může být přijatelné, pod 20% úplně bez problémů. Optimalizované verze budou dostupné na Metacentru a pod.

3) "Izolace". Otestovat, jaký má aplikace spuštěná pod dockrem přístup k hostujícímu souborovému systému. Nutné kvůli vstupním a výstupním operacím. Mělo by fungovat:

docker run -v /tmp:/root myImage

4) Testovat velikost image (pouze pro běh flow123d nikoliv pro překlad), velikost do 1GB je akceptovatelná do 500MB bez problémů.

**Comment by jbrezmorf** [comment]
Results:
ad 1.  test program compiled and running under docker under Windows is faster then same program compiled and running with cygwin
ad 2. Same results.
ad 3. Various directories may be mounted/shared under docker. No particular limitation.
ad 4. Developement images are about 1.3GB release images under 1GB.

**Comment by jbrezmorf** [comment]
@x3mSpeedy : Please check and correct results summarized in previous post and then close this issue.

**Comment by x3mSpeedy** [comment]
**Ad 1)** there is no clear answer to this assumption. In some cases Windows+cygwin will have upper hand over Windows+docker. 
Windows+cygwin are heavily influenced by IO operations which can take much longer compared to windows+docker. Big addition is windows+docker is MPI support (which can greatly reduce execution time). 

**Ad 2)** postponed until flow123d unit tests and int tests are fully running under docker. *(But I assume there will be difference since its running under ubuntu:16.04)*

**Ad 3)** in Linux environment, there are no limitation. In Windows all mounted directories must come from user home (default settings) this can by changes but requires manual intervention from administrator.

**Ad 4)** based on previous experience, both images (assuming they contain only *OS* + *flow123d* + *necessary tools and libs*) should fit in 1GB limit. *(estimating little over 500 MB)*
