### ISSUE TITLE
review reference element

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#637]
review ref_element after merge with intersections branch

**Comment by Paulie14** [comment]
master -> PE_intersection merge notes:

Do we want template function interact<> ? 
- advantages: single function, includes all possible dimension combinations
- disadvatages: dim parameters cannot be runtime variables, tricky call using template keyword
- if not, suggest proper names of functions/variables for node_of_subelements, edges_of_subelements, edges_connecting_node, faces_connecting_node etc... this is the reason, why I would stay with interact<>....

Barycentric coordinates
- unify functions
- interpolate with dim-subdim=1 does the same as barycentric_from_face

Do we want the function RefElement<dim>::count<subdim> instead of n_something and possibly for
n_something_per_something ?

**Comment by Paulie14** [comment]
Is discussed in #359.
