### ISSUE TITLE
Windows finish

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#776]
Results of tests on Windows (win 10 Jakub Říha, Lenovo JB).

Problems:
- users often have their data on various disks outside of Users
- flow123d and fterm are not in PATH, so their start from actual directory (to be mounted) is problematic
- fterm opens CMD window (ugly, can not resize, set font etc.)
- uninstall.sh does not uninstall other installed utilities: Docker, Git, Virtual Box
  Do we need Git? (POSTPONE solution)

Proposed solutions:
1. During install ask user for alternative directory to mount.
2. Add flow123d and fterm into PATH during install. Add to beginning to overwrite possible previous paths.
3. If runtest, fterm or flow123d is started from directory under flow123d installation, mount whole instalation (provide access to tests). Or mount it always.

**Comment by x3mSpeedy** [comment]
**Note to problems**
We do require `Git` because it contains `MinGW` which contains `bash`. This `bash` is then used to execute scripts such as `fterm.bat` or `flow123d.bat`. Therefore I don't understand how
> fterm opens CMD window (ugly, can not resize, set font etc.)

can occure.

**Note to proposed solutions**
Ad 1) not sure if possible (I wasn't able to mount other dirs under windows using GUI in VirtualBox more less automatize this process), but it is possible, [[link]](http://stackoverflow.com/questions/33245036/docker-toolbox-is-there-a-way-to-mount-other-folders-than-from-c-users-windows) and [[example]](http://stackoverflow.com/questions/35495639/docker-compose-mount-window-folder/35498478#35498478)
Ad 2) done
Ad 3) discussion required

**Comment by x3mSpeedy** [comment]
Ad 1) by editing `boot2docker.iso` image and sourcing additional script we are now able to mount other paths then `$HOME` (done in this commit  flow123d/docker-config@1cca6f5855845fec1c98cc3a9d083b9be9972d10)
