### ISSUE TITLE
slow sorptions

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#784]
Linearni sorpce volaji reinit pri kazdem vyhodnoceni, nepouzivaji se tabulky. Vysledkem je:

 vypocet bez sorpci 6s

vypocet s linearni sorpci: 134s

**Comment by jbrezmorf** [comment]
smb://jan.brezina@bacula.nti.tul.cz/intec/projekty/flow123d/input_data/bug_data/slow_sorption

**Comment by jstebel** [comment]
Sorptions are calculated by interpolation tables only if solubility or table_limits are given in the yaml file. Otherwise the sorption is calculated elementwise using a nonlinear solver.

**Comment by jbrezmorf** [comment]
We need to implement automatic extension of the tables.
TODO:
- if tables are not initialized pass through the conc values, determine range (0, max) of values and initailize tables for interval (0, 2*max). If solubility is set use range given by this parameter as is done now.
- during each calculation keep maximum of values out of tables, if this maximum is greater then table range, recompute tables using twice the new maximum as the upper bound

**Comment by Paulie14** [comment]
Finished by 1be74ab5f58faf3a383c6f370505225f2f4f1573
Can be closed when pull request  #968 is accepted.

This also fixed the following problem (now in test 30_sorption/11_direct_vs_interpolation):
- computing this simple problem with solubility limit did not give same results when computed directly or using interpolation
- problem was the solubility limit condition in direct computation, where it was done in the concentration axial system instead of total mass system
- is fixed in ccdfd66422a270ca25619ec21668b2ea425572d6

**Comment by jbrezmorf** [comment]
done
