### ISSUE TITLE
Improve GMSH output.

### ISSUE THREAD

**Issue by dflanderka** [flow123d/flow123d#882]
Modify GMSH to use output mesh not computing mesh. Deal with original IDs

**Comment by jbrezmorf** [comment]
- OutputElement::get_id() ... returns original ID for non-refined mesh and element index for refined mesh.
- ... need a flag in OutputMesh to indicate refined mesh.
- ?? How to get original IDs for nodes.

**Comment by jbrezmorf** [comment]
- Register more detailed information about output fields through: add_field_interpolation 
  in particular: field_name, discrete space, value type (n_elem = Scalar 1 , Vector 3, Tensor 9)
- use this data to decide between discontinuous or continuous mesh
- use it to initialize Dummy data list (see OutputMSH::write_field_data) ... during creating output mesh
- Simplify `write_field_data` rename to `add_dummy_fields` which add dummy fields that are not in output_data_list_
- call just write_xyz_data for the output_data_list[i_space_type]
- need to fix decision for discontinuous output mesh, do not use it for OutputMSH
- add methods get_node_ids_cache and get_element_ids_cache of OutputMesh to get ElementDataCache for original IDs of nodes and elements respectively. These are used only in GMSH output.

**Comment by jbrezmorf** [comment]
- Seems that decision for discontinuous output mesh can be same for GMSH and VTK, but we have to test how GMSH treats discontinuous meshes (i.e. we use NodeData on discont. mesh instead of ElementNodeData on continous mesh).

- make integration test for Node and Element data (continuous mesh)
- make integration test for Node, Element, Corner data (discontinuous mesh)
