### ISSUE TITLE
Optimization of output etc.

### ISSUE THREAD

**Issue by dflanderka** [flow123d/flow123d#901]
continuation of pull #888. 

- [x] Change from `vector<unsigned int>` to `vector<int>` in dofhadler::get_dof_indices, use own typedef
IdxInt as `int` for integers that are indices into large arrays (elements, nodes, dofs). 

- [x] Check if we can remove orig mesh from OutputTime at all so it should work only with OutputMesh and data caches
- [x] Can we remove dependency of OutputTime on OutputMesh? So it works only with data caches?
Introduce OutputTime::set_mesh_caches(nodes, conectivity, offsets, node_ids, elem_ids) 

- [x] Remove "OutputTime::is_parallel"
- [x] Move call of stream->get_output_mesh_ptr to compute_field_data and return null_ptr for case where current processor performs no output (and thus have no output mesh).

- [x] Test interpolated input and elementwise input in parallel.
- [x] Try to remove dependency of output_mesh on fields by passing a pointer to the function or rather std::function object. Create a lambda function from the `field->value_list(..)` passing the field itself as the closure parameter. Modify refinement methods to use just value_list call, evaluate at nodes and center in a single call.

**Comment by jbrezmorf** [comment]
- keep output_mesh_ in OutputTime object in order to share the mesh between several EquationOutput objects connected to the same output file (e.g. transport output, dual porosit, sorptions ...)
- modify EquationOutput::make_output_mesh to skip creation of the mesh if it already was set in OutputTime, reuse already created mesh
