### ISSUE TITLE
Idea - Matrix and RHS in ref output.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#953]
Have matrix and rhs in reference output at least in some test cases to detect changes in assembly.

- improve function for printing matrix and rhs to matlab format (already in some state in DarcyMH; similar used to be also directly in la classes; I remember bddc output was different and problematic in parallel)
- enable output matrix and rhs of the final system
- suggest which of the current integration tests are appropriate to have matrix and rhs in reference output (probably exclude long evolutionary models)

**Comment by jbrezmorf** [comment]
Due to limited space provided by GitHub we should keep only reference outputs that are necessary to detect errors in calculation. It is not meant to be a complete storage of data produced by previous versions. Moreover more extensive reference data set deteriorates maintenance. 

We can think about pstoring data from individual builds, but out of the repository.

**Comment by jbrezmorf** [comment]
Can possibly be part of ci-hpc test results DB. But in the view of lack of active development nearly no probability to do that.
