### ISSUE TITLE
Porosity  Output bug

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#987]
Reported by jiri.landa@tul.cz.
version: 2.1.2 commit: fbc1563

Porosity given as:
input_fields:
- region: A, B
  porosity: !FieldElementwise
- region: B
  porosity: 0.05

The value 0.05 is missing at the output for the time 0.0.

See input and output at:
`astra.nti.tul.cz/Public/jiri.landa/porosity_bug/`

```
Structure of transport.msh:

line     	content
4		$Nodes
		312980
		...
312987	$Elements
		1827245
		...
2140235	$ElementNodeData
		1
		"porosity"		# time 0.0
		...
		2002215 4 0.0098125 0.0098125 0.0098125 0.0098125 	# should be 0.05 here ??
		$EndElementNodeData
3967490	$ElementNodeData
		1
		"I129_conc"
		...
		2002215 4 0 0 0 0 
		$EndElementNodeData
5794745	$ElementNodeData
		1
		"porosity"		# time 1.0
		...
		2002215 4 0.05 0.05 0.05 0.05 
		$EndElementNodeData
7622000	$ElementNodeData
		1
		"I129_conc"
```

**Comment by Paulie14** [comment]
Problem appeared in DG transport due to different time schema (LimitSide:left).
The reason was that when different field on a region was found at the same input time,
instead of replacing, the field was added into the region history.
Is fixed in fcd22b3038389b8a5eb3f31957e312b5a21fbd47.

Created issue #989, inconsistent values at zero time in mass balance.
