### ISSUE TITLE
Zero time step mass balance - actual values of quantities

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#989]
Test34-02
After solving issue #987, there are nonzero fluxes in mass balance at zero time (transport DG).
So at zero time, the initial condition and boundary condition seem to be in conflict.
(for transport FV it is the same problem, and it was there even before #987)

For zero time actual values in balance, we think the values should be computed from init fields.
For cumulative balance, we think that the right limit values should be used (boundary conditions).

**Comment by jbrezmorf** [comment]
@Paulie14  @jstebel 

The problem is tough both because of the space scale of the matrix diffusion as because of the time scale of the plus boundary condition at `.right`. There is the `bc_flux = 1` prescribed till  `T = 18 000` and then it switch to the `inflow` with `bc_conc = 0`.

However the time step is set to `dt = 360 000` so the initial pulse can not be correctly resolved.

Resulting `mass_balance` have `flux_in = 0.001` at `T=0` and it remains zero for the subsequent timesteps.
The expected value is rather `1` equal to the prescribed flux, but possibly the `porosity = 1e-3` is involved.

Surprising is `flux_cumulative = 0` at `.right`, but `flux_cumulative = 17`` at `ALL`.

Definitely, the test should be reviewed, at least we should identify the problem(s).

**Comment by jstebel** [comment]
Explanation of current values in mass_balance.txt:
- Flux value 0.001 at initial time is the product of bc_flux and cross_section (the region .right stands for the right end of the fracture with cross_section=1).
- Lines with region names show actual values at given time (neither increments nor cumulative values). In case of flux at initial time it is questionable whether to compute from initial or boundary condition. Currently it is from b.c. consistently with other times.
- Line with region "ALL" has different meaning. It shows the cummulative values over the current computational time interval, which includes also times which were skipped by output (here it is t=18000).

Conclusion - things to improve:
- Decide whether to compute actual flux from initial condition.
- Make the balance files more readable. Avoid zeros where no values should be produced (replace e.g. by "-")
