### ISSUE TITLE
Difference in results for versions 2.2.0 and 2.1.2

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#996]
Substantial difference in balance and observation points between versions
2.2.0 PC (Ales Balvin) and 2.1.2 (charon).
See input and results:
	astra.cxi.tul.cz/models/milan.hokr/GREET-problem/

TODO:
- backport docker changes to 2.1.x branch
- reproduce on a same machine using same libraries (2.2.0  PC version run in docker using its libraries, 2.1.2 on Charon was built manually using same versions of libraries, but there can be some differences anyway).
- check changes in git that can contribute to the difference
- try to find source of the difference

**Comment by Paulie14** [comment]
- built branch PE_2.1.2
- have similar results on 2.2.1 and 2.1.2, regardless of rel/dbg
- I did not manage to reproduce results from Ales
- the fix in reading fields did not affect this

**Comment by Paulie14** [comment]
- built branch PE_2.1.2
- have similar results on 2.2.1 and 2.1.2, regardless of rel/dbg
- I did not manage to reproduce results from Ales
- the fix in reading fields did not affect this

- Ales has now consistent results, and he does not have original input data, so the problem was most probably on his side
- I fixed the observe data precision in master and 2.2.1, see #997

I consider the problem solved.
